name: Build Aseprite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++ cmake ninja-build libx11-dev libxcursor-dev libxi-dev \
            libgl1-mesa-dev libfontconfig1-dev

      - name: Download Skia
        run: |
          mkdir -p $HOME/deps
          cd $HOME/deps
          curl -LO https://github.com/aseprite/skia/releases/download/m81-b616b59-linux/skia-linux-Release-x64.zip
          unzip skia-linux-Release-x64.zip
          mv skia $HOME/deps/skia

      - name: Build Aseprite
        run: |
          mkdir -p build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=$HOME/deps/skia \
            -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
            -G Ninja ..
          ninja aseprite

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: aseprite
          path: build/bin/aseprite
